chuoi_s=input("nhập chuỗi s: ")
chuoi_s_sub=input("nhập chuỗi con s sup:")
s_find=input("nhập chuỗi tìm s find: ")
s_replace=input("nhập chuỗi thay thế s replace: ")
print(chuoi_s)
print(chuoi_s.center(10))
print(chuoi_s.count(chuoi_s_sub,0,16))
print(chuoi_s.find(s_find))
print(chuoi_s.replace("duck",s_replace))